name: Keep Render Awake

on:
  schedule:
    - cron: "*/12 * * * *"   # roda a cada 15 minutos
  workflow_dispatch:          # permite rodar manualmente se quiser

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl site
        run: |
          curl -fsS https://dnd-cc-ts9j.onrender.com/ || echo "ping falhou"
